In [2]:
import numpy as np

In [12]:
a = np.array([[1, 2, 3], [4, 5, 7]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 7]])

In [14]:
a.shape

(2, 3)

In [16]:
a[1][1]

5

In [17]:
a[1, 1]

5

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.random((2, 2))

array([[0.6143337 , 0.44566344],
       [0.07257826, 0.21062963]])

In [22]:
a = np.random.random((3, 3, 3))

In [23]:
a

array([[[0.04730292, 0.97257431, 0.62607498],
        [0.03658692, 0.47928758, 0.67362145],
        [0.81390174, 0.18278807, 0.53584233]],

       [[0.4730286 , 0.21837686, 0.64292794],
        [0.79767179, 0.56692077, 0.62088275],
        [0.3278366 , 0.10349313, 0.14300984]],

       [[0.36406054, 0.76416839, 0.82195099],
        [0.19806962, 0.78323111, 0.98066513],
        [0.67732581, 0.0173812 , 0.89890899]]])

In [25]:
a[:1,:1,:1]

array([[[0.04730292]]])

In [26]:
        a[1,2,:]

array([0.3278366 , 0.10349313, 0.14300984])

In [27]:
a.shape

(3, 3, 3)

In [28]:
a[1,2,:].shape

(3,)

In [35]:
np.arange(4)

array([0, 1, 2, 3])

In [36]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [37]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [39]:
res = np.dot(x, y)

In [40]:
res

array([[19., 22.],
       [43., 50.]])

In [41]:
res.T

array([[19., 43.],
       [22., 50.]])

In [42]:
from __future__ import print_function

In [43]:
import torch

In [47]:
x = torch.rand(5, 3)

In [48]:
print(x)

tensor([[0.4920, 0.0413, 0.5055],
        [0.7071, 0.5786, 0.4285],
        [0.0324, 0.2973, 0.7994],
        [0.7485, 0.7581, 0.7384],
        [0.7583, 0.3302, 0.2297]])
